package myP;

import java.awt.AWTException;
import java.awt.Robot;
import java.awt.event.KeyEvent;
import java.time.Duration;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.edge.EdgeDriver;

public class MyClass {
	public static void main(String[] Args) {
		
		
		
		/*for (int i=1;i<10;i++) {
			System.out.println("Md Shahajada Imran");
			System.setProperty("webdriver.edge.driver", "C:\\Users\\localadmin\\eclipse-workspace\\myP\\Browsers\\msedgedriver.exe");
			WebDriver driver=new EdgeDriver();
			driver.get("https://www.google.com/");
			driver.findElement(By.name("q")).sendKeys("Role");
			driver.findElement(By.name("btnK")).click();
			driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(10));
			
			driver.quit();
		}*/
		
		WebDriver driver=new EdgeDriver();
		driver.get("https://www.ups.com/");
		driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(3));
		driver.manage().window().maximize();
		driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(3));
		driver.findElement(By.cssSelector("#onetrust-close-btn-container > button")).click();
		driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(5));
		//Error Handling (pop-ups generated by Web site)
		try {
			Robot r=new Robot();
			r.keyPress(KeyEvent.VK_TAB);
			r.keyPress(KeyEvent.VK_TAB);
			r.keyPress(KeyEvent.VK_TAB);
			r.keyPress(KeyEvent.VK_ENTER);
			driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(5));
		} catch (AWTException e) {
			// TODO Auto-generated catch block
			//e.printStackTrace();
		}
		
		
		driver.findElement(By.id("tracking-numbers")).sendKeys("1234567890");
		driver.findElement(By.xpath("//*[@id=\"first section\"]/div/div/div[1]/div/div[2]/div/div/div/form/button")).click();
		
		//Text Checkpoint
		String vActualValue=driver.findElement(By.xpath("//*[@id=\"stApp_error_tittle0\"]/div/div[2]/div[1]/span")).getText();
		System.out.println(vActualValue);
		if(vActualValue.equals("Invalid tracking number")) {
			System.out.println("Checkpoint Passed");
		}else {
			System.out.println("Failed");
		}
		
		
		
		
		
		
	}

}
