package myP;

import java.awt.AWTException;
import java.awt.Robot;
import java.awt.event.KeyEvent;
import java.time.Duration;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.edge.EdgeDriver;

public class TestCase101 {
	//TestCase No: 101
	//TestCase Name: "Invalid Traking Number" text displays if wrong traking number is used.
	//TestCase Type: Negative Testing, Functional Testing
	//Created and automated By: Md Shahajada Imran
	//Framework: Core Java code 
	
	public static void main(String[] Args) {
		
		WebDriver driver=new EdgeDriver();
		driver.get("https://www.ups.com/");
		driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(3));
		driver.manage().window().maximize();
		driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(3));
		driver.findElement(By.cssSelector("#onetrust-close-btn-container > button")).click();
		driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(5));
		//Error Handling (pop-ups generated by Web site)
		try {
			Robot r=new Robot();
			r.keyPress(KeyEvent.VK_TAB);
			r.keyPress(KeyEvent.VK_TAB);
			r.keyPress(KeyEvent.VK_TAB);
			r.keyPress(KeyEvent.VK_ENTER);
			driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(5));
		} catch (AWTException e) {
			// TODO Auto-generated catch block
			//e.printStackTrace();
		}
		
		
		driver.findElement(By.id("tracking-numbers")).sendKeys("1234567890");
		driver.findElement(By.xpath("//*[@id=\"first section\"]/div/div/div[1]/div/div[2]/div/div/div/form/button")).click();
		
		//Text Checkpoint
		String vActualValue=driver.findElement(By.xpath("//*[@id=\"stApp_error_tittle0\"]/div/div[2]/div[1]/span")).getText();
		System.out.println(vActualValue);
		if(vActualValue.equals("Invalid tracking number")) {
			System.out.println("Checkpoint Passed");
		}else {
			System.out.println("Failed");
		}
		
		
		
		
		
		
	}
	

}
